<?php

/**
 * @file
 * To alter the Signup form and add few more fields.
 */

use Drupal\Core\Url;

/**
 * Alter the login form.
 */
function signupform_form_alter(&$form, $form_state, $form_id) {
  if ($form['#form_id'] == 'personalForm') {

    $form['fullname']['#attributes']['placeholder'] = t('Fullname');
    $form['username']['#attributes']['placeholder'] = t('Username');
    $form['pass']['#attributes']['placeholder'] = t('Password');

    $form['pass-toggle'] = [
      '#type' => 'label',
      '#label' => 'show',
      '#attributes' => [
        'class' => 'pass-toggle show',
      ],
      '#title' => t('Show'),
    ];

    $form['agree-description'] = [
      '#markup' => '<div class="signup-description">By signing up you agree to our <b>Terms</b>,<b>Data Policy</b> and <b>Cookie Policy</b></div>',
    ];

    $form['my-empty-container'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => 'my-class',
      ],

      'left' => [
        '#type' => 'item',
        'sub' => [],
      ],

      'child' => [
        '#type' => 'item',
        '#title' => t('OR'),
      ],

      'right' => [
        '#type' => 'item',
        'sub' => [],
      ],
    ];

    $form['icon-block'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => 'icon-block',
      ],

      'facebook' => [
        '#type' => 'link',
        '#attributes' => [
          'class' => 'facebook',
        ],
        '#prefix' => '<i class="fab fa-facebook-square"></i>',
        '#title' => t('Log in with Facebook'),
        '#url' => Url::fromUri('https://www.facebook.com/'),
      ],

    ];

    $order = ['Heading', 'icon-block', 'my-empty-container', 'pass-toggle', 'name', 'fullname', 'username', 'pass',
      'actions', 'password', 'agree-description',
    ];
    foreach ($order as $key => $field) {
      $form[$field]['#weight'] = $key;
    }

  }
}
