hashtags.settings:
  type: config_object
  label: 'Hashtags Advanced Settings'
  mapping:
    hashtags_taxonomy_terms_field_name:
      type: string
      label: 'Hashtags taxonomy terms field name'
    hashtags_vid:
      type: string
      label: 'Hashtags vocabulary'
    hide_field_hashtags:
      type: boolean
      label: 'Hide hashtags field?'