<?php

/**
 * @file
 * To store the variables that are been displayed on the profile page.
 */

/**
 * Implements hook_theme().
 */
function profile_block_theme() {
  return [
    'user-profile-block' => [
      'variables' => [
        'uname' => NULL,
        'display_current' => NULL,
        'display_other' => NULL,
        'post_count' => NULL,
        'followers_count' => NULL,
        'following_count' => NULL,
        'name' => NULL,
        'bio' => NULL,
        'followers_link' => NULL,
        'following_link' => NULL,
        'attached' => NULL,
      ],
    ],

    'flag-modal' => [
      'variables' => [
        'uri' => NULL,
        'uname' => NULL,
        'name' => NULL,
        'post_count' => NULL,
        'followers_count' => NULL,
        'following_count' => NULL,
        'post_uri_all' => NULL,
        'link' => NULL,
        'flag_txt_unfollow' => NULL,
        'flag_txt_remove' => NULL,
        'flag_link' => NULL,
      ],
    ],
  ];
}
