<?php
 
function profile_block_theme($existing, $type, $theme, $path) {
  return [

    'user-profile-block' => [
      'variables' => [ 
          'uname' => NULL,  
          'post_count' => NULL,
          'followers_count' => NULL,
          'following_count' => NULL,  
          'name' => NULL, 
          'bio' => NULL, 
          'markup1' => NULL,
          'markup2' => NULL,
          'attached' => NULL,
      ],
    ],

    'flag-modal' => [
      'variables' => [   
        'uri' => NULL,  
        'uname' => NULL, 
        'name' => NULL,  
        'post_count' => NULL, 
        'followers_count' => NULL, 
        'following_count' => NULL, 
        'post_uri_all' => NULL,  
        'link' => NULL, 
        'flag_txt' => NULL,  
        'flag_link' => NULL,   
      ],
    ],
  ];
}
