<?php

/**
 * @file
 * Contains mumodule.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_entity_view().
 */
function mumodule_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityType()->id() === 'node') // Because entity object is passed.
  {
    $build['awesome'] = [
      '#markup' => '<marquee>This is very awesome.</marquee>',
      '#allowed_tags' => ['marquee'],
    ];
  }
}
/**
 * Implements hook_theme().
 */
function mumodule_theme() {
  return [
    'mumodule' => [
      'render element' => 'children',
    ],
  ];
}
