name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2021-11-03
version: '9.2.8'
project: 'drupal'
datestamp: 1635961278
